name: Clippy

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust Tests
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
