name: Rust Test

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weaversa/cryptol-course:2.13
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: cargo test -- --nocapture
