name: Rust Formatter

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Tests
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check
