name: Rust Test

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/galoisinc/cryptol-remote-api:2.13.0
        ports:
          - 3829:3829
        options:
          --entrypoint ["http", "--host", "0.0.0.0", "--port", "8080", "/"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust Tests
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: cargo test -- --nocapture
        env:
          CRYPTOL_SERVER_URL: http://cryptol-remote-api:3829
