name: Rust Formatter

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust Tests
        uses: dtolnay/rust-toolchain@stable
        with: 
          components: rustfmt
      - run: cargo fmt --all -- --check
