name: Rust Test

on: [push, pull_request]

jobs:
  rust-test:
    runs-on: ubuntu-latest
    services:
      cryptol-remote-api:
        image: ghcr.io/galoisinc/cryptol-remote-api:2.13.0
        ports:
          - 8080:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust Tests
        uses: actions-rs/toolchain@v1
        with: 
          toolchain: stable
      - run: cargo test -- --nocapture
        env:
          CRYPTOL_SERVER_URL: http://localhost:8080
